export enum DiseaseCategory {
  INFECTIOUS_RESPIRATORY = 'INFECTIOUS_RESPIRATORY',
  INFECTIOUS_GASTROINTESTINAL = 'INFECTIOUS_GASTROINTESTINAL',
  INFECTIOUS_OTHER = 'INFECTIOUS_OTHER',
  CARDIOVASCULAR = 'CARDIOVASCULAR',
  METABOLIC = 'METABOLIC',
  CHRONIC_RESPIRATORY = 'CHRONIC_RESPIRATORY',
  MUSCULOSKELETAL = 'MUSCULOSKELETAL',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  NEUROLOGICAL = 'NEUROLOGICAL',
  CANCER = 'CANCER',
  AUTOIMMUNE = 'AUTOIMMUNE',
  ALLERGY = 'ALLERGY',
}
